language: node_js
node_js:
    - '10'

# set cache
cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - npm run build

after_script:
    - cd .vuepress/dist

    - git config user.name "${U_NAME}"

    - git config user.email "${U_EMAIL}"

    - git init

    - git add -A

    - git commit -m "deploy"

    - git push -f "https://${GH_TOKEN}@github.com/${U_NAME}/${GH_REPO}" master:${P_BRANCH}

branches:
    only:
        - master
